name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: Rhodes-IS-Analyst-Linux
          - os: macos-latest
            asset_name: Rhodes-IS-Analyst-macOS
          - os: windows-latest
            asset_name: Rhodes-IS-Analyst-Windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller build.spec --noconfirm --clean --onefile

      - name: Prepare artifact for upload (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifact
          move dist/${{ matrix.asset_name }} artifact
        shell: cmd

      - name: Prepare artifact for upload (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir artifact
          mv dist/${{ matrix.asset_name }} artifact/
          cd artifact
          zip -r ../${{ matrix.asset_name }}.zip .
          cd ..

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifact/${{ matrix.asset_name }}*
            ${{ matrix.asset_name }}.zip